### ISSUE TITLE
TRANSLATION:absolute-path

### ISSUE THREAD

**Issue by nbdutra** [PsyTeachR/glossary#106]
Comment: I am not sure if the names in [ ] can be translations, I did not do this for the "alpha" translation (see beta distribution and cronbach's alpha in the alpha entry translation).

<div class="translation" lang="br-pt">

<dfn> caminho absoluto: um caminho para um arquivo que começa com / e não está fixado ao diretório de trabalho</dfn>

Por exemplo, se o seu [diretório de trabalho](w.html#working-directory) é `/Users/me/study/` e você quer se referir a um arquivo no diretório `data` chamado `faces.csv`, o caminho absoluto é `/Users/me/study/data/faces.csv`.

Entretanto, você deve normalmente usar [caminhos relativos](r.html#relative-path) nos scripts, não caminhos absolutos, pois estes podem mudar quando você move o diretório de um projeto para um computador novo ou até mesmo para um destino novo no seu computador. 

O pacote R.utils possui uma função `getAbsolutePath()` que retorna o caminho absoluto de um arquivo [caminho](p.html#path) ou um arquivo[objeto](o.html#object)

</div>

**Comment by debruine** [comment]
You're right, the link URLs will always be to the english version (like "v.html#vector") and the linked text can be any language.
