### ISSUE TITLE
New: NaN and Inf definition?

### ISSUE THREAD

**Issue by ASarafoglou** [PsyTeachR/glossary#123]
## NaN

<dfn>An impossible number that is "Not a number"</dfn>

In `R` impossible number are represented with the symbol `NaN`. Use the function `is.nan()` to check if values are impossible numbers.

```{r nan-exp1}
value <- 0/0
value
is.nan(value)
```

## Inf

<dfn>A value representing positive infinity</dfn>

In `R` infinity is represented with the symbol `Inf`. Use the function `is.infinite()` to check if values are infinite.

```{r nan-exp1}
value <- 1/0
value
is.infinite(1/0)

# negative infinity
value <- -1/0
value
is.infinite(1/0)

```

**Comment by debruine** [comment]
These are great, thanks!
