### ISSUE TITLE
NEW: Outlier

### ISSUE THREAD

**Issue by philmcaleer** [PsyTeachR/glossary#31]
Would be good to include maybe a paper on detecting outliers as well

**Comment by debruine** [comment]
I added this paper. Feel free to suggest others:

Leys, C., Delacre, M., Mora, Y. L., Lakens, D., & Ley, C. (2019). How to Classify, Detect, and Manage Univariate and Multivariate Outliers, With Emphasis on Pre-Registration. International Review of Social Psychology, 32(1), 5. DOI: <a href="http://doi.org/10.5334/irsp.289">10.5334/irsp.289</a>
