### ISSUE TITLE
idea: function to display definition in text rather than term

### ISSUE THREAD

**Issue by philmcaleer** [PsyTeachR/glossary#61]
Might be an idea to have a function that displays the definition of a word in the actual body of text in a paragraph, rather than the word.  Say for example:

"Degrees of Freedom is defined as `r glossary_show_definition("degrees of freedom")`

Which would knit as:

"Degrees of Freedom is defined as The number of observations that are free to vary to produce a known outcome."

though might need to put a `tolower()` around it.  That way people would only need to update the definition in the glossary and it would update in other places it is used and remove any inconsistencies. Might not be frequently used but could be handy.

**Comment by debruine** [comment]
Done, use the `show_def` argument to the glossary function after you download the new version 0.0.0.9002
