### ISSUE TITLE
NEW: atomic

### ISSUE THREAD

**Issue by JackEdTaylor** [PsyTeachR/glossary#80]
[Vectors]((v.html#vector)) are atomic because all [objects](o.html#object) inside them are the same type (e.g., all [numeric](n.html#numeric) or [character](c.html#character)).

```{r}
a <- c(1, 4, 32)
b <- c("somebody", "once", "told me")
class(a)
class(b)
```

If you try to mix data types in an atomic vector, they will be [coerced](c.html#coercion) to be the same type. (Note that `32` becomes `"32"` so it can be in the same vector as a character object).

```{r}
c(32, "eighteen")
```

Another feature of vectors which makes them atomic is that they are always flat. If you embed vectors within vectors, they will be flattened.

```{r}
c(7, c(1, 4, 32), 2, 6)
```

If you try to extract objects inside an atomic vector, you need to use `[]`. This can be with an [index](i.html#index) or a name.

```{r}
my_vec <- c(x = 3, y = 1, z = 4)
my_vec[2]
my_vec["y"]
```

You cannot use the `$` [operator](o.html#operator) on an atomic vector, or you will get this very common [error](e.html#error).

```{r eval=FALSE}
my_vec$y
```

```
Error in my_vec$y : $ operator is invalid for atomic vectors
```

**Comment by debruine** [comment]
Thanks! This is really clear.
