### ISSUE TITLE
TRANSLATION:alpha

### ISSUE THREAD

**Issue by nbdutra** [PsyTeachR/glossary#95]
Translation to (Brazilian) Portuguese

(I think it is pt, not sure)
<div class="translation" lang="pt"> 

<dfn>([stats](a.html#alpha-stats)) alfa: o valor limite para tomar uma decisão ao rejeitar uma hipótese nula; [graphics](a.html#alpha-graphics)) um valor entre 0 e 1 usado para controlar os níveis de transparência em um gráfico</dfn>

Pode ser também um parâmetro na distribuição beta [beta distribution](b.html#beta-distribution) ou se referir ao alfa de Cronbach [Cronbach's alpha](c.html#cronbachs-alpha).

</div>

**Comment by debruine** [comment]
Awesome, thank you! That should be online in a few minutes
